"""
lang_graph_agent.py — SAFEE LangGraph-style orchestrator.

Wires every node into a sequential pipeline and returns the final
GraphState dict.  In production, swap the linear pipeline for a real
LangGraph StateGraph with conditional edges for retries / branching.
"""

from __future__ import annotations

import traceback
from typing import Any, Dict

# removed unused GraphState import
from planner_node import planner_node
from rag_node import rag_node, repo_state_node
from guardrail_node import guardrail_node
from code_generator import codet5p_node
from code_encoder import graphcodebert_validate_node
from tier1_test_runner import test_runner_tier1_node
from retry_cost_mem import retry_control_node, cost_budget_node, failure_memory_node
from telemetry_node import observability_node
from human_approval import human_approval_node


async def run_safe_agent(
    user_id: str,
    raw_requirement: str,
    repo_context: dict,
    project_state: dict,
    vulnerable_code: str = "",
    allow_human_approval: bool = True,
    allow_ci_inject: bool = False,
) -> Dict[str, Any]:
    """
    Execute the full SAFEE pipeline and return the enriched state.
    """

    # ── Bootstrap state ─────────────────────────────────────────
    state: Dict[str, Any] = {
        "user_id": user_id,
        "raw_requirement": raw_requirement,
        "repo_context": repo_context,
        "project_state": project_state,
        "vulnerable_code": vulnerable_code,
        "retries": 0,
        "total_cost_usd": 0.0,
        "failures": [],
        "telemetry_events": [],
        "deployed": False,
    }

    try:
        # 1. Planner — parse requirement
        state.update(planner_node(state))

        # 2. RAG + repo grounding
        state.update(rag_node(state))
        state.update(repo_state_node(state))

        # 3. Code generation (CodeT5+)
        state.update(codet5p_node(state))

        # 4. Guardrail check on generated code
        state.update(guardrail_node(state))

        # 5. GraphCodeBERT validation
        state.update(graphcodebert_validate_node(state))

        # 6. Tier-1 tests (lint, unit, SAST)
        state.update(test_runner_tier1_node(state))

        # 7. Retry / cost tracking
        state.update(retry_control_node(state))
        state.update(cost_budget_node(state))

        # 8. Failure memory + telemetry
        state.update(failure_memory_node(state))
        state.update(observability_node(state))

        # 9. Human approval (if enabled)
        if allow_human_approval:
            state.update(human_approval_node(state))
        else:
            state["human_approved"] = None

        # 10. CI injection trigger (GitHub Automation)
        if allow_ci_inject and state.get("human_approved"):
            from github_service import create_fix_pr
            
            # Use the relative file path from the raw requirement or assume a default for the demo.
            # In a real scenario, the LLM/Planner would extract the exact file path.
            target_file = state.get("repo_context", {}).get("target_file", "main.py")
            patched_code = state.get("patch", "")
            
            commit_msg = f"Fix: Auto-generated patch for {target_file}"
            pr_title = f"SAFEE Fix: {commit_msg}"
            pr_body = f"This PR was automatically generated by SAFEE to address a flagged vulnerability.\n\n### Requirement\n{state.get('raw_requirement')}"
            
            success, result_msg = create_fix_pr(
                require_path=target_file,
                patched_code=patched_code,
                commit_msg=commit_msg,
                pr_title=pr_title,
                pr_body=pr_body
            )
            
            state["ci_approved"] = success
            state["ci_results"] = {"status": "pr_created" if success else "failed", "details": result_msg}
        else:
            state["ci_approved"] = False
            state["ci_results"] = None

        return state

    except Exception as exc:
        # Capture the failure and still return a usable state
        state.setdefault("failures", []).append({
            "error": str(exc),
            "traceback": traceback.format_exc(),
        })
        state.update(observability_node(state))
        state["human_approved"] = False
        state["deployed"] = False
        return state
